import type { SceneContent } from "@/types/content";

/**
 * The 12-scene journey — ARCHITECTURE.md §1.2 (Rev 2), BLUEPRINT.md §4.
 * Order, anchors, light stages, and motion primitives are load-bearing:
 * <Experience> renders this array directly, in order, with no scene
 * reordering or omission logic. Copy follows the DESIGN.md §2 voice rules
 * (short declarative sentences, full stops, present tense, never selling).
 */
export const scenes: SceneContent[] = [
  {
    id: "enter",
    order: 1,
    anchor: "#enter",
    label: "Enter The Estate",
    lightStage: "morning-mist",
    headline: "Hidden Within The Nilgiri Hills",
    subheadline:
      "A private estate where waterfalls, tea plantations and unforgettable stays come together.",
    body: ["Cascade Rocks"],
    mediaSlots: ["enter.hero"],
    motionPrimitive: "scene-travel",
    pinned: true,
  },
  {
    id: "valley",
    order: 2,
    anchor: "#valley",
    label: "Discover The Valley",
    lightStage: "morning-mist",
    headline: "Discover The Valley",
    mediaSlots: ["valley.flyover"],
    body: [
      "45 Minutes From Ooty.",
      "25 Minutes From Coonoor.",
      "Far From The Crowds.",
      "Close To Nature.",
    ],
    motionPrimitive: "scene-travel",
    pinned: true,
  },
  {
    id: "private",
    order: 3,
    anchor: "#private",
    label: "The Private Estate",
    lightStage: "morning-mist",
    headline: "The Private Estate",
    body: [
      "No Crowds.",
      "No Shared Spaces.",
      "Only Your Group.",
      "Only Nature.",
      "Only The Hills.",
    ],
    mediaSlots: ["private.gate", "private.veranda", "private.table"],
    motionPrimitive: "editorial-reveal",
    pinned: false,
  },
  {
    id: "estate",
    order: 4,
    anchor: "#estate",
    label: "Estate Overview",
    lightStage: "midday-clarity",
    headline: "One Estate. Entirely Yours.",
    subheadline:
      "Nine bedrooms, four living rooms, a courtyard that opens onto a waterfall, and an acre of lawn — seen as one.",
    mediaSlots: ["estate.overview"],
    motionPrimitive: "scene-travel",
    pinned: true,
  },
  {
    id: "stay",
    order: 5,
    anchor: "#stay",
    label: "Your Stay",
    lightStage: "golden-hour",
    headline: "Your Stay",
    subheadline: "Explored, not listed.",
    body: [
      "Nine Queen Bedrooms.",
      "Seven Bathrooms, Each With Its Own Geyser.",
      "Four Living Rooms That Become More Bedrooms When You Need Them.",
      "A Courtyard That Opens Onto A Waterfall.",
    ],
    mediaSlots: ["stay.bedroom", "stay.living", "stay.bathroom", "stay.dining"],
    motionPrimitive: "scrubbed-exploration",
    pinned: true,
  },
  {
    id: "table",
    order: 6,
    anchor: "#table",
    label: "The Table",
    lightStage: "golden-hour",
    headline: "Meals Made With Care",
    subheadline: "Subrata Pandey. Fifteen Years Of Craft.",
    mediaSlots: ["table.chef", "table.dish", "table.hall"],
    motionPrimitive: "depth-parallax",
    pinned: false,
  },
  {
    id: "experiences",
    order: 7,
    anchor: "#experiences",
    label: "Estate Experiences",
    lightStage: "golden-hour",
    headline: "Estate Experiences",
    subheadline: "Each one a memory waiting to be discovered.",
    mediaSlots: [
      "experiences.teaFactory",
      "experiences.waterfallTrek",
      "experiences.strawberryFarm",
      "experiences.cattleShed",
      "experiences.bonfire",
    ],
    motionPrimitive: "scrubbed-exploration",
    pinned: true,
  },
  {
    id: "nature",
    order: 8,
    anchor: "#nature",
    label: "Meet Nature",
    lightStage: "dusk",
    headline: "Meet Nature",
    body: [
      "Wake Up To Birdsong.",
      "Listen To Flowing Water.",
      "Watch The Mist Roll Across The Hills.",
      "Let Nature Set The Pace.",
    ],
    mediaSlots: ["nature.tree"],
    motionPrimitive: "editorial-reveal",
    pinned: false,
  },
  {
    id: "comfort",
    order: 9,
    anchor: "#comfort",
    label: "Modern Comforts",
    lightStage: "evening",
    headline: "Modern Comforts",
    subheadline: "Quiet conveniences, never the point — always in place.",
    body: [
      "Fiber Broadband WiFi.",
      "Music System, Karaoke & A Dancing Zone.",
      "UPS Backup.",
      "Geysers In Every Bathroom.",
      "A Dedicated Bonfire Area.",
    ],
    mediaSlots: ["comfort.lamp", "comfort.lights"],
    motionPrimitive: "depth-parallax",
    pinned: false,
  },
  {
    id: "stories",
    order: 10,
    anchor: "#stories",
    label: "Guest Stories",
    lightStage: "evening",
    headline: "Guest Stories",
    subheadline: "In their own words.",
    mediaSlots: ["stories.veranda"],
    motionPrimitive: "editorial-reveal",
    pinned: false,
  },
  {
    id: "plan",
    order: 11,
    anchor: "#plan",
    label: "Plan Your Escape",
    lightStage: "evening",
    headline: "Plan Your Escape",
    body: [
      "Group Stays.",
      "Family Vacations.",
      "Corporate Retreats.",
      "Parking For A Tempo Traveller Or Six Cars.",
    ],
    mediaSlots: ["plan.lawn"],
    motionPrimitive: "editorial-reveal",
    pinned: false,
  },
  {
    id: "book",
    order: 12,
    anchor: "#book",
    label: "Book Your Stay",
    lightStage: "evening",
    headline: "Your Nilgiri Escape Awaits",
    subheadline: "Carry this calm into your stay.",
    mediaSlots: ["book.hero"],
    motionPrimitive: "scene-travel",
    pinned: true,
  },
];

export function getSceneById(id: string): SceneContent | undefined {
  return scenes.find((scene) => scene.id === id);
}
